server:
 port: 9001
spring:
 application:
  name: lineus-base
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql:///lineus_base?serverTimezone=UTC
  username: root
  password: 123456
 jpa:
  show-sql: true
  generate-ddl: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka/
  instance:
    prefer-ip-address: true 
     
